package com.meridian.yamcs.webpage;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

import org.yamcs.AbstractPlugin;
import org.yamcs.ConfigurationException;
import org.yamcs.PluginException;
import org.yamcs.Spec;
import org.yamcs.YConfiguration;
import org.yamcs.security.SystemPrivilege;
import org.yamcs.web.WebPlugin;

/**
 * Yamcs plugin that registers a yamcs-web extension which adds a sidebar item
 * embedding an external webpage in the main content area.
 * <p>
 * The plugin itself is intentionally thin: all behaviour lives in the bundled
 * web extension ({@code external-webpage.js}). This plugin only:
 * <ol>
 * <li>reads the standalone configuration file {@code etc/external-webpage.yaml},</li>
 * <li>registers the configured system privilege with the security module, and</li>
 * <li>hands the prebuilt web bundle and configuration to {@link WebPlugin}.</li>
 * </ol>
 * <p>
 * The plugin <em>name</em> (= the Maven artifactId, {@code external-webpage}) is
 * significant: yamcs-web instantiates a custom element named after it and routes
 * its page at {@code /<instance>/ext/<name>}. It must match the custom-element tag
 * defined in the web extension.
 * <p>
 * The displayed name and the URL are not hard-coded: they come from the configuration
 * file {@code etc/external-webpage.yaml} ({@code label} / {@code url}) and can be changed
 * without rebuilding.
 */
public class ExternalPagePlugin extends AbstractPlugin {

    /** Classpath folder where the built web bundle is packaged (see plugin/pom.xml). */
    private static final String BUNDLE_RESOURCE_DIR = "/webpage-extension";
    /** Lists the bundle files to extract (generated by the web build, see finalize.mjs). */
    private static final String BUNDLE_MANIFEST = "manifest.txt";

    /** Standalone config file name: resolves to {@code etc/external-webpage.yaml}. */
    private static final String CONFIG_SUBSYSTEM = "external-webpage";

    private static final String DEFAULT_GROUP = "archive";
    private static final String DEFAULT_ICON = "public";

    @Override
    public Spec getSpec() {
        // No options are expected in yamcs.yaml; configuration lives in etc/external-webpage.yaml.
        return new Spec();
    }

    @Override
    public void init() throws PluginException {
        var webPlugin = yamcs.getPluginManager().getPlugin(WebPlugin.class);
        if (webPlugin == null) {
            log.warn("yamcs-web (WebPlugin) is not installed; "
                    + "the '{}' external-page extension will not be registered.", pluginName);
            return;
        }

        YConfiguration config;
        try {
            config = YConfiguration.getConfiguration(CONFIG_SUBSYSTEM);
        } catch (ConfigurationException e) {
            log.warn("No 'etc/{}.yaml' found; the '{}' external-page extension will not be registered.",
                    CONFIG_SUBSYSTEM, pluginName);
            return;
        }

        // Resolve the list of pages. Either an explicit 'pages:' list, or a single page from
        // top-level 'label'/'url'/... keys (backward compatible with the original config).
        String topGroup = config.getString("group", DEFAULT_GROUP);
        List<YConfiguration> pageConfigs;
        if (config.containsKey("pages")) {
            pageConfigs = config.getConfigList("pages");
        } else if (config.containsKey("label") && config.containsKey("url")) {
            pageConfigs = List.of(config);
        } else {
            throw new PluginException("etc/" + CONFIG_SUBSYSTEM
                    + ".yaml must define a 'pages' list (or a top-level 'label' and 'url').");
        }

        var pages = new ArrayList<Map<String, Object>>();
        var labels = new ArrayList<String>();
        var registeredPrivileges = new HashSet<String>();
        int index = 0;
        for (YConfiguration p : pageConfigs) {
            if (!p.containsKey("label") || !p.containsKey("url")) {
                throw new PluginException("Each page in etc/" + CONFIG_SUBSYSTEM
                        + ".yaml must define 'label' and 'url'.");
            }
            String label = p.getString("label");
            String url = p.getString("url");
            // Omitted, blank or '*' privilege means "no gate" -> visible to all users.
            String privilege = p.getString("privilege", "");
            String icon = p.getString("icon", DEFAULT_ICON);
            String group = p.getString("group", topGroup);
            int order = p.getInt("order", index);

            boolean gated = !privilege.isBlank() && !"*".equals(privilege.trim());
            if (gated && registeredPrivileges.add(privilege)) {
                // Register so it is assignable to roles in the security module
                // (superusers always pass; everyone else needs the privilege).
                yamcs.getSecurityStore().addSystemPrivilege(new SystemPrivilege(privilege));
            }

            var page = new HashMap<String, Object>();
            page.put("label", label);
            page.put("url", url);
            page.put("privilege", privilege);
            page.put("icon", icon);
            page.put("group", group);
            page.put("order", order);
            pages.add(page);
            labels.add(label);
            index++;
        }

        // The whole page list is passed to the web app and read by the extension at runtime,
        // so pages/labels/URLs can be changed in etc/external-webpage.yaml without rebuilding.
        Map<String, Object> extensionConfig = new HashMap<>();
        extensionConfig.put("pages", pages);

        Path staticRoot = extractWebBundle();

        // The extension id must equal the plugin name so yamcs-web instantiates the
        // matching custom element <external-webpage>.
        webPlugin.addExtension(pluginName, extensionConfig, staticRoot);

        log.info("Registered external-page extension with {} page(s): {}", pages.size(), labels);
    }

    /**
     * Extracts the bundled web files (an Angular Elements build: one or more .js/.css
     * files) from the plugin jar to a temporary directory, which is then served by
     * yamcs-web as an extra static root. The set of files is read from a manifest
     * generated by the web build.
     */
    private Path extractWebBundle() throws PluginException {
        try {
            Path dir = Files.createTempDirectory("external-webpage-");
            dir.toFile().deleteOnExit();

            for (String file : readManifest()) {
                String resource = BUNDLE_RESOURCE_DIR + "/" + file;
                Path target = dir.resolve(file);
                try (InputStream in = getClass().getResourceAsStream(resource)) {
                    if (in == null) {
                        throw new PluginException("Missing bundled web resource: " + resource
                                + " (the web extension was not built into the plugin jar).");
                    }
                    Files.copy(in, target);
                }
                target.toFile().deleteOnExit();
            }
            return dir;
        } catch (IOException e) {
            throw new PluginException("Could not extract the web extension bundle", e);
        }
    }

    private List<String> readManifest() throws PluginException, IOException {
        String resource = BUNDLE_RESOURCE_DIR + "/" + BUNDLE_MANIFEST;
        try (InputStream in = getClass().getResourceAsStream(resource)) {
            if (in == null) {
                throw new PluginException("Missing bundled web resource: " + resource
                        + " (the web extension was not built into the plugin jar).");
            }
            var files = new ArrayList<String>();
            var reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (!line.isEmpty()) {
                    files.add(line);
                }
            }
            if (files.isEmpty()) {
                throw new PluginException("Web extension manifest is empty: " + resource);
            }
            return files;
        }
    }
}
