services:
  yamcs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: estrack-yamcs-demo:latest
    container_name: estrack-yamcs-demo
    ports:
      - "8090:8090"
    restart: unless-stopped
